name: sac
params:
  _target_: agent.sac.SACAgent
  obs_dim: ???  # to be specified later
  action_dim: ???  # to be specified later
  action_range: ???  # to be specified later
  device: ${device}
  discount: 0.8
  init_temperature: 0.1
  alpha_lr: 1e-4
  alpha_betas: [0.9, 0.999]
  actor_lr: 1e-4
  actor_betas: [0.9, 0.999]
  actor_update_frequency: 1
  critic_lr: 1e-4
  critic_betas: [0.9, 0.999]
  critic_tau: 0.005
  critic_target_update_frequency: 2
  batch_size: 1024
  learnable_temperature: true
  critic: ${critic}
  actor: ${actor}